### ISSUE TITLE
Snapshot Links Update

### ISSUE THREAD

**Issue by Alero-Awani** [layer5labs/kanvas-snapshot#123]
### Current Behavior

Some link updates are needed for pull request snapshots.

### Desired Behavior

1. Replace the documentation link under the snapshot with [Interpreting Meshery Designs](https://meshery.layer5.io/academy/learning-paths/mastering-meshery/introduction-to-meshery?chapter=interpreting-meshery-designs)

2. Add a link that directs users to the design on the Meshery Playground.

3. Allow users to click on the snapshot to expand the image.

### Screenshots / Mockups

<img width="952" alt="Screenshot 2024-09-18 at 3 48 03 PM" src="https://github.com/user-attachments/assets/819470cd-9eb0-4b0f-b2f9-5ff7fab8bf2c">

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Raghav1783** [comment]
i want to work on this

**Comment by Raghav1783** [comment]
@Alero-Awani after making changes how will i test my changes ?
